[workspace]
authors = ["Josh Weinstock <josh.weinstock@emory.edu>"]
channels = ["conda-forge", "bioconda"]
name = "GWAS_neale_lab"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
duckdb-cli = ">=1.3.1,<2"
zlib = ">=1.3.1,<2"
liblzma = ">=5.8.1,<6"
readline = ">=8.2,<9"
xz = ">=5.8.1,<6"
libxml2 = ">=2.14.4,<3"
r = ">=4.4,<4.5"
r-renv = ">=1.1.4,<2"
libcurl = ">=8.14.1,<9"
python = ">=3.13.5,<3.14"
polars = ">=1.31.0,<2"
numpy = ">=2.3.0,<3"
ucsc-liftover = ">=482,<483"
ruff = ">=0.12.0,<0.13"
